name: digs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=22.3.1
  - mkl==2024.0
  - numpy==2.0.0
  - tqdm
  - tensorboard
  - tensorboardX
  - pyyaml
  - pip:
    - opencv-python
    - matplotlib
    - pydicom
    - tifffile
    - imagecodecs
    - pyvista
    - SimpleITK
    - scikit-image
    - Cython==0.29.36
    - open3d==0.18.0
    - -e digs/submodules/simple-knn
    - -e digs/submodules/fast-free-form-deformation
    - -e digs/submodules/xray-gaussian-rasterization-voxelization
    - itk
    - itk-rtk
    - nibabel